var beatles = [String]()
beatles.append("Pele")
beatles.append("Qele")
beatles.append("Rele")
beatles.append("Sele")
print(beatles)
beatles.reverse()
print(beatles)
beatles.remove(at:2)
print(beatles.count)
print(beatles)
